%
% Set specific model parameters which match a given regular expression 
%   to random values generated by a uniform distribution 
% 
% call: 
%     [simopt,nct] = setSimParReg(simopt,reg,lowerval,upperval)
%
%  simopt : A simulation structure set by the call setSimulation
%  reg      : regular expression matching parameter name 
%  pval     : parameter value
%  lowerval : the lowest random value allowed to be generated 
%  upperval: the largest random value allowed to be generated
%  ncnt      : number of times reg was matched 
% 
%  Author:  Atiyah Elsheikh
%  Date:     22.11.2011 
% 
function [simopt,ncnt] = setSimParRegUniform(simopt,reg,lowerval,upperval)

    npars = length(simopt.plabels); 
    mat = regexp(simopt.plabels,reg); 
    ncnt = 0; 
    for i=1:npars 
        if(~isempty(mat{i}))
            ncnt = ncnt + 1;
            simopt.pvalues(i) = rand * (upperval - lowerval) + lowerval; 
        end
    end
    
end